### ISSUE TITLE
[Feature] access info settings at cluster config level 

### ISSUE THREAD

**Issue by shawncao** [varchar-io/nebula#134]
Right now - we're supporting table level access info passing for each table definition in the cluster config. This works fine if the cluster works with many different data sources, but if most tables are repeating the same settings, it is not ideal.

We should introduce a cluster level security info in the next version of cluster config which could kick in when table level settings is missing. But when table level is presenting, they acts as overwriting the cluster level settings. 

Something like:

```yaml
Azure:
    azure.account: xxx
    azure.secret: yyy
S3:
   s3.account: aaa
   s3.secret: bbb
Kafka:
   kafka.protocol: SASL
```
etc.
